### PR TITLE
Disable automerge, enable Grayskull checking and fix PyPI URL

### LINKED ISSUE #9: Consider using Grayskull
To simplify updating dependency constraints, it may be worth [configuring Grayskull in conda-forge.yml]( https://conda-forge.org/docs/maintainer/conda_forge_yml/#bot ) like so

```yaml
bot:
  inspection: update-grayskull
```

This way the bot will refresh dependencies during updates as well

### LINKED ISSUE #11: PyPI `source/url` should replace `pypi.io` with `pypi.org`
> PyPI default URL is now pypi.org, and not pypi.io. You may want to update the default source url.

_Originally posted by @conda-forge-admin in https://github.com/conda-forge/array-api-strict-feedstock/issues/8#issuecomment-2463508674_

### PR DESCRIPTION
**Pull request by rgommers**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes gh-9
Closes gh-11
Follows up on gh-13

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks Ralf! 🙏

The linter error would be fixed by following the recently added [CFEP 25]( https://github.com/conda-forge/cfep/blob/main/cfep-25.md )

Once done we could add a "fixes" note for issue: https://github.com/conda-forge/array-api-strict-feedstock/issues/10

Edit: Added a "fixes" note for issue ( https://github.com/conda-forge/array-api-strict-feedstock/issues/11 ), which you already fixed in this PR

**Comment by rgommers** [comment]
> The linter error would be fixed by following the recently added [CFEP 25](https://github.com/conda-forge/cfep/blob/main/cfep-25.md)

I looked at the link, but I don't like that at all. Adding `{{ python_min }}` and then defining `python_min` in a separate file is just obscure indirection for no real reason as far as I can tell. It's very hard to understand such constructs unless you're intimately familiar with conda-forge (it's not like the variable is imported so it's obvious where it comes from).

**Comment by rgommers** [comment]
The rationale in the CFEP makes sense for excluding too-old versions no longer supported by conda-forge, but it doesn't discuss the case where a package only supports a _newer_ version well enough. 

Something like a double constraint `>={{ python_min }}, >=3.10` could make sense.

**Comment by rgommers** [comment]
I couldn't even easily find what the current value of `python_min` was - it took time to locate it:

https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/a15fa36d14319f4045acefbff2dd3a55ed454f80/recipe/conda_build_config.yaml#L796-L799

This really should be easier to introspect for the average feedstock maintainer.

**Comment by jakirkham** [comment]
Thanks Ralf! 🙏

This is good feedback. Would it be possible to consolidate this feedback in issue ( https://github.com/conda-forge/conda-forge.github.io/issues/2351 )? That would really help us with tracking it

As this is a recent CFEP, fully expect there is room for improvement

**Comment by rgommers** [comment]
Thanks, I'll do that! Will try to add some suggestions about what would have helped me.

**Comment by asmeurer** [comment]
I don't think we should disable automerge.

**Comment by rgommers** [comment]
> I don't think we should disable automerge.

Why not? It's pretty trivial to review and merge a PR, just a quick look at changelog, lints, etc. Automerge is apparently dangerous. I think even aside from the review opportunity, one of the advantages of a delay of 1-2 days is that regressions do not affect conda-forge users. This is actually quite valuable - PyPI users can report the obvious regressions.

**Comment by asmeurer** [comment]
It's an extra step, and one that I will probably forget to do when making a release, especially given that the bot tends to have a delay.

**Comment by asmeurer** [comment]
Going to merge this and leave the automerge off for now because I want to make sure the next release is correct. But I do think we should turn it back on in the future.

**Comment by jakirkham** [comment]
> It's an extra step, and one that I will probably forget to do when making a release, especially given that the bot tends to have a delay.

It's possible to [request a bot update]( https://conda-forge.org/docs/maintainer/infrastructure/#conda-forge-admin-please-update-version ), which will pick up the new version and now dependencies

Does this project have a release process checklist? If so, maybe this can be an item there

**Comment by asmeurer** [comment]
Can that be done automatically in the GitHub Actions job that does the release?

**Comment by jakirkham** [comment]
Can that GHA job raise an issue on a different repo?

**Comment by asmeurer** [comment]
Yeah, that's the question. I have no idea if that's possible. I'm assuming not. I guess we could try adding `gh issue create` to the job and seeing if it works.

**Comment by jakirkham** [comment]
Yeah it's a question of how to configure the permissions correctly

If you find a solution that works for you, would be interested to hear about it. Would imagine this is useful in more places

Ofc the other angle would be teaching the bot to subscribe to webhooks: https://github.com/regro/cf-scripts/issues/18

**Comment by rgommers** [comment]
> Will try to add some suggestions about what would have helped me.

I wanted to do this this morning, and then noticed I'm not the only one with this feedback. The docs now explicitly address the "lower version is newer" case and there is now a way to define `python_min` inside `meta.yaml` (see [docs](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python)). So I think I'm happy with the current state now - will incorporate `python_min` in a future PR.

**Comment by jakirkham** [comment]
Glad to hear that Ralf! 🙏

If you think of more feedback, please let us know 🙂

**Pull request merged**
